import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "../../global-context";
import Navigation from "../components/navigation";
import Footer from "../components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Wrap the children with your provider */}
        <GlobalProvider initialLocales={undefined}>
          <Navigation />
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  )
}