import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "../../global-context";
import Navigation from "../components/navigation";
import NasdaqTicker from "../components/nasdaq-ticker";
import Footer from "../components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { allFontVariables } from './fonts';
import ThemeWrapper from '../components/ThemeWrapper';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={allFontVariables} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                let mode = 'dark';
                const stored = localStorage.getItem('voltgrid-theme-storage');
                if (stored) {
                  const parsed = JSON.parse(stored);
                  if (parsed.state && parsed.state.mode) {
                    mode = parsed.state.mode;
                  }
                }
                if (mode === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body>
        <GlobalProvider initialLocales={undefined}>
          <ThemeWrapper>
            <div className="flex flex-col min-h-screen w-full">
              <Navigation />
              <NasdaqTicker />
              <div className="flex-grow flex flex-col w-full">
                {children}
              </div>
              <Footer />
            </div>
          </ThemeWrapper>
        </GlobalProvider>
      </body>
    </html>
  )
}