import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "../../global-context";
import Navigation from "../components/navigation";
import Footer from "../components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { allFontVariables } from './fonts';
import ThemeWrapper from '../components/ThemeWrapper';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={allFontVariables}>
      <body>
        <GlobalProvider initialLocales={undefined}>
          <ThemeWrapper>
            <Navigation />
            {children}
            <Footer />
          </ThemeWrapper>
        </GlobalProvider>
      </body>
    </html>
  )
}